# Generated by Django 5.0.7 on 2024-07-19 00:45

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maintenancelog',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipmentdata',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 0, 45, 7, 53024)),
        ),
        migrations.AddField(
            model_name='equipmentdata',
            name='well_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='equipment_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='equipment_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='last_maintenance_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 0, 45, 7, 53057)),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='maintenance_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 0, 45, 7, 53347)),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 0, 45, 7, 42807)),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='well_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
