# Generated by Django 5.0.7 on 2024-07-22 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_remove_equipmentdata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdata',
            name='installation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 10, 5, 42, 439719)),
        ),
        migrations.AlterField(
            model_name='equipmentdata',
            name='last_maintenance_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 10, 5, 42, 439750)),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='maintenance_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 10, 5, 42, 440006)),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 10, 5, 42, 430390)),
        ),
    ]
